### ISSUE TITLE
Develop style system for online offerings that share common features

### ISSUE THREAD

**Issue by petercolesdc** [dotmesh-io/brand-design#1]
A way in which we can set a base template of styles, but also propagate and update certain pieces across offerings over time.

**Comment by petercolesdc** [comment]
[design-system-0.1.pdf](https://github.com/datamesh-io/brand-design/files/1502251/design-system-0.1.pdf)

Initial idea

**Comment by petercolesdc** [comment]
[design-system-0.2.pdf](https://github.com/datamesh-io/brand-design/files/1588867/design-system-0.2.pdf)

Updated version that better reflects current Hugo workflow

**Comment by lukemarsden** [comment]
This appears to be done. Please re-open if it's not.
