### ISSUE TITLE
Plan and decide upon a UX -> Design -> Deploy strategy

### ISSUE THREAD

**Issue by petercolesdc** [dotmesh-io/brand-design#15]
It would make a lot of sense to me to start this discussion now, even if we don't fully start with it until we're in Alpha stage.

I think we should try to draw up a flow from how a new feature (or change or anything) goes from inception, through UX and design and into development and how it flows around (as these things are not linear). 

Some user testing between UX and design and design and development would make a lot of sense, and should happen as often as we can make it happen. 

Not sure what devices / browsers we're aiming to support (I'm guessing we're being fairly progressive) but testing should be done for releases, ideally in the gap between front-end design finishing and development starting on the feature.

I'm keen to keep this process somewhat fluid, but an underpinning would be good to nail down,

**Comment by lukemarsden** [comment]
I think we have a better sense of how we're doing this now, so closing.
