### ISSUE TITLE
Circle of Control graphic

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/brand-design#18]

**Comment by petercolesdc** [comment]
![dothub_circle_of_control](https://user-images.githubusercontent.com/118106/35855186-6841803e-0b2a-11e8-94a7-3aa69dd4eabe.png)

**Comment by petercolesdc** [comment]
@lukemarsden @mrmrcoleman ^ graphic for the COC

**Comment by petercolesdc** [comment]
Done and added here - https://github.com/dotmesh-io/brand-design/tree/master/diagrams
