### ISSUE TITLE
Mesh graphic

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/brand-design#19]

**Comment by petercolesdc** [comment]
![dothub_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35813654-0f377abe-0a8c-11e8-80c9-f0a453f2ce9c.png)
![dothub_developer_collaboration](https://user-images.githubusercontent.com/118106/35813655-0f577a26-0a8c-11e8-9065-f52490331dea.png)
![dothub_realistic_data_in_production](https://user-images.githubusercontent.com/118106/35813656-10348812-0a8c-11e8-8bc2-dd2d756ff02f.png)

Three graphics, following from the Keynote presentation, for marketing purposes. These are high-res. Reduce physic size for online use please

**Comment by petercolesdc** [comment]
Smaller for web use

![dothub_web_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35814720-a482e476-0a8e-11e8-9eac-6315c8e1ef4b.png)
![Uploading dothub_web_developer_collaboration.png…]()
![Uploading dothub_web_realistic_date_from_production.png…]()

**Comment by petercolesdc** [comment]
@lukemarsden @mrmrcoleman - let me know if these are OK

**Comment by petercolesdc** [comment]
P.S seeing them in context now, I think they could do with larger labels.

**Comment by lukemarsden** [comment]
yes, much bigger labels please. they need to work if a journo has cnp'd them at low res and pasted them into a small image section in an article

**Comment by lukemarsden** [comment]
can we make the green worlds the same size please? also the labels for the green worlds should be "environments" not "infrastructure"

otherwise, these are looking great!

**Comment by mrmrcoleman** [comment]
Hey @petercolesdc would it be possible to also get a single image with all 3 use cases on it? Perhaps by adding arrows to point out the 3 interactions between the environments and the hub?

Happy to jump on a call to show you what I mean.

**Comment by petercolesdc** [comment]
![dothub_web_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35820827-c58669a8-0a9e-11e8-995b-e88b390c9e01.png)
![dothub_web_developer_collaboration](https://user-images.githubusercontent.com/118106/35820828-c5acc8dc-0a9e-11e8-99ef-0694e8b3d291.png)
![Uploading dothub_web_realistic_date_from_production.png…]()

Updated. Worlds now almost the same size (keep a little difference as an Isometric grid has perspective, but this is more subtle). Labels much larger.

**Comment by petercolesdc** [comment]
@mrmrcoleman - yes, we could different colour lines. It _might_ be a bit busy and muddled mind you.

**Comment by petercolesdc** [comment]
![dothub_web_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35821470-fcb57890-0aa0-11e8-9ab7-d470471de3c9.png)
![Uploading dothub_web_developer_collaboration.png…]()
![Uploading dothub_web_realistic_date_from_production.png…]()

**Comment by petercolesdc** [comment]
![dothub_web_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35821509-1962a8c8-0aa1-11e8-8d32-45a581e387bf.png)
![dothub_web_developer_collaboration](https://user-images.githubusercontent.com/118106/35821511-19818086-0aa1-11e8-817f-6692a4601c74.png)
![dothub_web_realistic_date_from_production](https://user-images.githubusercontent.com/118106/35821512-19a02c16-0aa1-11e8-9888-4197dbfdea4c.png)

**Comment by petercolesdc** [comment]
![dothub_web_capture_failed_ci_runs](https://user-images.githubusercontent.com/118106/35822593-b351bd2c-0aa4-11e8-8bd0-4dd9653898b2.png)
![dothub_web_developer_collaboration](https://user-images.githubusercontent.com/118106/35822595-b3cb2d4c-0aa4-11e8-8aca-8e11e5fe0943.png)
![dothub_web_dotmesh_dothub](https://user-images.githubusercontent.com/118106/35822596-b3fa14b8-0aa4-11e8-98b8-d31527c5478b.png)
![dothub_web_realistic_date_from_production](https://user-images.githubusercontent.com/118106/35822597-b431266a-0aa4-11e8-946a-6754031efccf.png)

**Comment by petercolesdc** [comment]
Done
