### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/brand-design#20]

**Comment by petercolesdc** [comment]
Where can one find this diagram, so I can re-make it (im sure it's here somewhere, I just can't see where)

**Comment by petercolesdc** [comment]
![concrete_architecture](https://user-images.githubusercontent.com/118106/35865479-8775c48e-0b4c-11e8-8e9e-0030b81379aa.png)

PNG rather than SVG due to expanse of type (which is an embed issue)

**Comment by petercolesdc** [comment]
Done
