### ISSUE TITLE
Slidedeck templates

### ISSUE THREAD

**Issue by petercolesdc** [dotmesh-io/brand-design#7]
Format/s to be discussed. Create a set template for slide presentations

**Comment by lukemarsden** [comment]
Keynote and Google Presentation please :)

**Comment by petercolesdc** [comment]
@lukemarsden - 16:9 and 4:3 ratios also? Annoyingly I don't think you can adapt one template (at least not in Keynote).

**Comment by lukemarsden** [comment]
I always just do 16:9

**Comment by petercolesdc** [comment]
No worries. We can always cross the 4:3 bridge when we come to it
